"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,ArrowRight,CalendarDays,Check,CheckCircle2,Clock3,CreditCard,Download,FileText,Luggage,Mail,Plane,Printer,ShieldCheck,Smartphone,TicketCheck,UserRound,WalletCards} from "lucide-react";

const fares=[
 {name:"Economy Lite",price:6125000,bag:"20 kg",features:["Cabin baggage 7 kg","Checked baggage 20 kg","Standard meal included","Seat selection: Additional fee","Reschedule: Fee applies","Refund: Not available"]},
 {name:"Economy Standard",price:6475000,bag:"30 kg",recommended:true,features:["Cabin baggage 7 kg","Checked baggage 30 kg","Standard meal included","Standard seat included","Reschedule: Reduced fee","Partial refund"]},
 {name:"Economy Flex",price:6950000,bag:"30 kg",features:["Cabin baggage 7 kg","Checked baggage 30 kg","Seat selection included","No airline change fee","Refund available","Priority support"]}
];
const steps=["Fare","Traveler","Add-ons","Review","Payment","Confirmation"];
const money=(n:number)=>`IDR ${n.toLocaleString("id-ID")}`;
const addonPrices:Record<string,number>={"Seat 21A":175000,"Extra baggage 10 kg":425000,"Travel insurance":185000,"Airport lounge":275000};

export default function BookingPage(){
 const [stage,setStage]=useState(0),[fare,setFare]=useState(1),[addons,setAddons]=useState<string[]>([]),[meal,setMeal]=useState("Halal Meal"),[seatOpen,setSeatOpen]=useState(false),[payment,setPayment]=useState("Virtual Account"),[processing,setProcessing]=useState(0),[seconds,setSeconds]=useState(899),[confirmed,setConfirmed]=useState(false),[ticket,setTicket]=useState(false),[promo,setPromo]=useState("");
 const [traveler,setTraveler]=useState({title:"Mr",name:"Ahmad Pratama",gender:"Male",dob:"1991-08-17",nationality:"Indonesian",passport:"C1234567",country:"Indonesia",issue:"2023-02-10",expiry:"2033-02-09",email:"ahmad.pratama@email.com",mobile:"+62 812 3456 7890",ffp:"",emergency:"Siti Pratama · +62 811 2233 4455"});
 const [ack,setAck]=useState(false),[terms,setTerms]=useState(false),[paying,setPaying]=useState(false);
 useEffect(()=>{const t=window.setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[]);
 const addonTotal=addons.reduce((n,a)=>n+(addonPrices[a]||0),0),discount=promo.toUpperCase()==="AEROWISATA10"?250000:0,tax=785000,total=fares[fare].price+tax+addonTotal-discount;
 const progress=stage>=5?5:stage;
 const next=()=>{window.scrollTo({top:0,behavior:"smooth"});setStage(s=>Math.min(7,s+1))};
 const toggle=(a:string)=>setAddons(v=>v.includes(a)?v.filter(x=>x!==a):[...v,a]);
 const startPayment=()=>{setPaying(true);setStage(5);let i=0;const t=window.setInterval(()=>{i++;setProcessing(i);if(i>=4){clearInterval(t);window.setTimeout(()=>{setConfirmed(true);setStage(6)},650)}},850)};
 const stepIndex=(i:number)=>i===5?stage>=6?5:stage:i;
 return <main className="checkout-page">
  <header className="checkout-header"><a href="/demo?member=personal&role=Individual%20Member" className="checkout-brand"><span className="brand-mark"><i/><i/><i/></span><span className="brand-copy"><b>Aerowisata</b><small>GARUDA INDONESIA GROUP</small></span></a><div><ShieldCheck/><span><b>Secure booking</b><small>Your data is encrypted and protected</small></span></div></header>
  <nav className="booking-progress" aria-label="Booking progress">{steps.map((s,i)=><div className={stepIndex(i)<progress?"done":stepIndex(i)===progress?"active":""} key={s}><i>{stepIndex(i)<progress?<Check/>:i+1}</i><span>{s}</span></div>)}</nav>
  {stage===5?<Processing state={processing}/>:stage===6?<Confirmation total={total} fare={fares[fare]} addons={addons} onTicket={()=>{setTicket(true);setStage(7)}}/>:stage===7?<Ticket fare={fares[fare]} total={total} traveler={traveler} seat={addons.includes("Seat 21A")?"21A":"—"}/>:<div className="checkout-shell"><section className="checkout-content">
   {stage===0&&<><PageTitle title="Choose Your Fare" sub="Select the fare that best matches your travel needs."/><FlightStrip/><div className="fare-grid">{fares.map((f,i)=><article key={f.name} className={fare===i?"selected":""}>{f.recommended&&<b className="recommended-badge">Recommended</b>}<h3>{f.name}</h3><div className="fare-price"><strong>{money(f.price)}</strong><small>/ passenger</small></div><ul>{f.features.map(x=><li key={x}><Check/> {x}</li>)}</ul><button onClick={()=>setFare(i)}>{fare===i?<><Check/> Selected</>:`Select ${f.name.split(" ")[1]}`}</button></article>)}</div><div className="fare-foot"><button>Compare Fare Benefits</button><button>View Fare Rules</button><span><TicketCheck/> Only 4 seats remaining at this price</span></div></>}
   {stage===1&&<><PageTitle title="Traveler Details" sub="Enter the traveler’s information exactly as shown on the passport."/><div className="profile-actions"><button onClick={()=>setTraveler({...traveler,name:"Ahmad Pratama"})}><UserRound/> Use My Profile</button><button>Select Saved Passenger</button><button>Add New Traveler</button></div><FormSection title="Personal Information"><Fields data={traveler} set={setTraveler} keys={[["title","Title"],["name","Full Name"],["gender","Gender"],["dob","Date of Birth"],["nationality","Nationality"]]}/></FormSection><FormSection title="Travel Document"><Fields data={traveler} set={setTraveler} keys={[["passport","Passport Number"],["country","Issuing Country"],["issue","Passport Issue Date"],["expiry","Passport Expiry Date"]]}/><p className="form-help"><CheckCircle2/> Passport validity meets destination requirements.</p></FormSection><FormSection title="Contact & Optional Information"><Fields data={traveler} set={setTraveler} keys={[["email","Email Address"],["mobile","Mobile Number"],["ffp","Frequent Flyer Number (optional)"],["emergency","Emergency Contact"]]}/></FormSection><label className="check-row"><input type="checkbox"/> Save this traveler to my Saved Passengers.</label><label className="check-row"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I confirm that the traveler information is correct.</label></>}
   {stage===2&&<><PageTitle title="Enhance Your Journey" sub="Personalize your trip with optional services."/><div className="addon-grid"><Addon icon={<Plane/>} title="Seat Selection" text={addons.includes("Seat 21A")?"Selected: 21A · Preferred window":"Choose standard, preferred, or extra legroom seats."} button="Select Seat" active={addons.includes("Seat 21A")} onClick={()=>setSeatOpen(true)}/><Addon icon={<Luggage/>} title="Extra Baggage" text="Add 10 kg checked baggage." price="IDR 425.000" button={addons.includes("Extra baggage 10 kg")?"Remove":"Add Baggage"} active={addons.includes("Extra baggage 10 kg")} onClick={()=>toggle("Extra baggage 10 kg")}/><Addon icon={<FileText/>} title="Meal Preference" text={meal} button="Change Meal" onClick={()=>setMeal(meal==="Halal Meal"?"Vegetarian Meal":"Halal Meal")}/><Addon icon={<ShieldCheck/>} title="Travel Insurance" text="Cancellation, medical, baggage, and delay protection." price="IDR 185.000" button={addons.includes("Travel insurance")?"Remove":"Add Insurance"} active={addons.includes("Travel insurance")} onClick={()=>toggle("Travel insurance")}/><Addon icon={<WalletCards/>} title="Airport Lounge" text="Comfortable lounge access before departure." price="IDR 275.000" button={addons.includes("Airport lounge")?"Remove":"Add Lounge"} active={addons.includes("Airport lounge")} onClick={()=>toggle("Airport lounge")}/></div>{seatOpen&&<SeatMap onClose={()=>setSeatOpen(false)} onSelect={()=>{if(!addons.includes("Seat 21A"))toggle("Seat 21A");setSeatOpen(false)}}/>}</>}
   {stage===3&&<><PageTitle title="Review Your Booking" sub="Check all details carefully before continuing to payment."/><Review title="Flight Details"><FlightStrip/><div className="review-facts"><span>Cabin<b>Economy</b></span><span>Fare type<b>{fares[fare].name}</b></span><span>Baggage<b>{fares[fare].bag}</b></span></div></Review><Review title="Traveler Details"><div className="review-facts"><span>Passenger<b>{traveler.name}</b></span><span>Nationality<b>{traveler.nationality}</b></span><span>Passport<b>••••{traveler.passport.slice(-4)}</b></span><span>Expiry<b>{traveler.expiry}</b></span></div></Review><Review title="Add-ons"><p>{addons.length?addons.join(" · "):"No paid add-ons selected"} · {meal}</p></Review><Review title="Member Benefits"><div className="promo"><input placeholder="Promo code" value={promo} onChange={e=>setPromo(e.target.value)}/><button>Apply</button><span>Available points: <b>4,850</b></span></div>{discount>0&&<p className="promo-ok"><CheckCircle2/> AEROWISATA10 applied — you save {money(discount)}</p>}</Review><div className="warning-box">Passenger names and travel documents may not be editable after ticket issuance.</div><label className="check-row"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I have reviewed and confirmed that all traveler details are correct.</label><label className="check-row"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/> I agree to the fare rules, cancellation policy, privacy policy, and terms.</label></>}
   {stage===4&&<><PageTitle title="Complete Your Payment" sub="Choose a secure payment method to complete your booking."/><div className="payment-total"><small>Total payment</small><strong>{money(total)}</strong><span>Price includes taxes and fees</span></div><div className="payment-tabs">{["Virtual Account","Credit / Debit Card","QRIS","E-Wallet","Bank Transfer"].map(p=><button className={payment===p?"active":""} onClick={()=>setPayment(p)} key={p}><CreditCard/>{p}</button>)}</div><div className="payment-panel">{payment==="Virtual Account"&&<><h3>Select your bank</h3><div className="bank-grid">{["BCA","Mandiri","BNI","BRI"].map((b,i)=><button className={i===0?"active":""} key={b}>{b}<small>Virtual Account</small></button>)}</div></>}{payment==="Credit / Debit Card"&&<><h3>Card details</h3><div className="field-grid"><label>Cardholder Name<input placeholder="Name on card"/></label><label>Card Number<input placeholder="0000 0000 0000 0000"/></label><label>Expiry Date<input placeholder="MM / YY"/></label><label>CVV<input placeholder="•••"/></label></div><label className="check-row"><input type="checkbox"/> Save this card securely with my consent.</label></>}{payment==="QRIS"&&<div className="qris"><div className="qr-pattern"/><div><h3>Scan with your payment app</h3><p>QR code will expire in 14:42</p><button>Refresh payment status</button></div></div>}{!['Virtual Account','Credit / Debit Card','QRIS'].includes(payment)&&<div className="wallet-list"><h3>Select {payment}</h3><button>GoPay</button><button>OVO</button><button>DANA</button></div>}</div><div className="secure-row"><span><ShieldCheck/> Secure Payment</span><span><CheckCircle2/> Encrypted Transaction</span><span><UserRound/> Privacy Protection</span></div></>}
   <footer className="checkout-actions"><button className="back" onClick={()=>stage===0?location.href="/":setStage(s=>s-1)}><ArrowLeft/> {stage===0?"Back to Flight Results":"Back"}</button>{stage===2&&<button className="skip" onClick={next}>Skip for Now</button>}<button className="continue" disabled={(stage===1&&!ack)||(stage===3&&(!ack||!terms))||paying} onClick={stage===4?startPayment:next}>{stage===4?`Pay ${money(total)}`:stage===0?"Continue to Traveler Details":stage===1?"Continue to Add-ons":stage===2?"Continue to Review":"Continue to Payment"}<ArrowRight/></button></footer>
  </section><TripSummary fare={fares[fare]} addons={addons} tax={tax} discount={discount} total={total} seconds={seconds}/></div>}
 </main>
}

function PageTitle({title,sub}:{title:string,sub:string}){return <header className="checkout-title"><p>INDIVIDUAL MEMBER · B2C</p><h1>{title}</h1><span>{sub}</span></header>}
function FlightStrip(){return <article className="selected-flight"><span className="flight-logo"><Plane/></span><div><b>Garuda Indonesia</b><small>GA 980 · Economy · Direct</small></div><strong>11:35<small>CGK</small></strong><i><small>10h 45m</small><span/></i><strong>18:20<small>JED</small></strong><div className="flight-date"><CalendarDays/><span><small>Thursday</small><b>14 May 2026</b></span></div></article>}
function TripSummary({fare,addons,tax,discount,total,seconds}:{fare:any,addons:string[],tax:number,discount:number,total:number,seconds:number}){return <aside className="trip-summary"><div className={seconds<300?"timer warning":"timer"}><Clock3/><span>Price held for <b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</b></span></div><h2>Trip Summary</h2><div className="summary-route"><b>CGK</b><span><Plane/><i/></span><b>JED</b></div><p>Jakarta → Jeddah</p><dl><div><dt>Garuda Indonesia</dt><dd>GA 980</dd></div><div><dt>Thu, 14 May 2026</dt><dd>11:35 – 18:20</dd></div><div><dt>Passenger</dt><dd>1 Adult</dd></div><div><dt>Cabin</dt><dd>Economy</dd></div><div><dt>Selected fare</dt><dd>{fare.name}</dd></div></dl><div className="price-lines"><span>Base fare<b>{money(fare.price)}</b></span><span>Taxes & fees<b>{money(tax)}</b></span>{addons.map(a=><span key={a}>{a}<b>{money(addonPrices[a])}</b></span>)}{discount>0&&<span className="discount">Discount<b>− {money(discount)}</b></span>}<strong>Total amount<b>{money(total)}</b></strong></div><small className="summary-note">Taxes, airport charges, and service fees are included.</small></aside>}
function FormSection({title,children}:{title:string,children:any}){return <section className="form-section"><h2>{title}</h2>{children}</section>}
function Fields({data,set,keys}:{data:any,set:any,keys:string[][]}){return <div className="field-grid">{keys.map(([k,l])=><label key={k}>{l}<input type={k.includes("dob")||k.includes("issue")||k.includes("expiry")?"date":"text"} value={data[k]} onChange={e=>set({...data,[k]:e.target.value})}/></label>)}</div>}
function Addon({icon,title,text,price,button,active,onClick}:{icon:any,title:string,text:string,price?:string,button:string,active?:boolean,onClick:()=>void}){return <article className={active?"addon active":"addon"}><span>{icon}</span><div><h3>{title}</h3><p>{text}</p>{price&&<b>{price}</b>}</div><button onClick={onClick}>{active&&<Check/>}{button}</button></article>}
function Review({title,children}:{title:string,children:any}){return <section className="review-card"><header><h2>{title}</h2><button>Edit</button></header>{children}</section>}
function SeatMap({onClose,onSelect}:{onClose:()=>void,onSelect:()=>void}){const seats=Array.from({length:36},(_,i)=>i+1);return <div className="seat-modal"><div><header><div><p>GARUDA INDONESIA · GA 980</p><h2>Select Your Seat</h2></div><button onClick={onClose}>×</button></header><div className="seat-legend"><span><i/>Available</span><span><i className="preferred"/>Preferred</span><span><i className="occupied"/>Occupied</span></div><div className="aircraft"><div className="cockpit">Flight deck</div><div className="seats">{seats.map(n=><button disabled={[3,7,11,16,23,29].includes(n)} className={n===21?"preferred":""} onClick={n===21?onSelect:undefined} key={n}>{Math.ceil(n/6)}{String.fromCharCode(65+(n-1)%6)}</button>)}</div></div><footer><span>Selected seat: <b>21A · Preferred window</b></span><button onClick={onSelect}>Confirm Seat · IDR 175.000</button></footer></div></div>}
function Processing({state}:{state:number}){const s=["Confirming payment","Reserving your seat","Creating booking reference","Issuing your ticket"];return <section className="processing-page"><div className="processing-plane"><Plane/></div><p>PLEASE WAIT</p><h1>Processing Your Booking</h1><span>Please do not close or refresh this page.</span><div>{s.map((x,i)=><article className={i<state?"done":i===state?"active":""} key={x}><i>{i<state?<Check/>:i+1}</i><b>{x}</b><small>{i<state?"Completed":i===state?"In progress...":"Waiting"}</small></article>)}</div><small>Your payment is protected. This usually takes less than a minute.</small></section>}
function Confirmation({total,fare,addons,onTicket}:{total:number,fare:any,addons:string[],onTicket:()=>void}){return <section className="confirmation-page"><CheckCircle2/><p>BOOKING CONFIRMED</p><h1>Your Flight Is Booked!</h1><span>Your booking and e-ticket have been successfully issued.</span><div className="status-row"><b><i/>Booking Confirmed</b><b><i/>Payment Paid</b><b><i/>Ticket Issued</b></div><article><header><span>Booking reference / PNR<strong>AW7K9P</strong></span><span>E-ticket number<strong>126-9876543210</strong></span></header><FlightStrip/><div className="confirmation-facts"><span>Passenger<b>Ahmad Pratama</b></span><span>Seat<b>{addons.includes("Seat 21A")?"21A":"To be assigned"}</b></span><span>Baggage<b>{fare.bag}</b></span><span>Total paid<b>{money(total)}</b></span></div></article><div className="confirm-actions"><button onClick={onTicket}><TicketCheck/> View E-ticket</button><button onClick={()=>window.print()}><Download/> Download E-ticket</button><button><Mail/> Email E-ticket</button><button><CalendarDays/> Add to Calendar</button></div><div className="trip-added"><CheckCircle2/> Your booking has been added to My Trips.</div><nav><a href="/demo?member=personal&role=Individual%20Member">View My Trips</a><button>Book Airport Transfer</button><button>Book Hotel</button><a href="/demo?member=personal&role=Individual%20Member">Return to Dashboard</a></nav></section>}
function Ticket({fare,total,traveler,seat}:{fare:any,total:number,traveler:any,seat:string}){return <section className="ticket-page"><header><div className="checkout-brand"><span className="brand-mark"><i/><i/><i/></span><span className="brand-copy"><b>Aerowisata</b><small>E-TICKET ITINERARY</small></span></div><span className="ticket-status"><CheckCircle2/> TICKET ISSUED</span></header><div className="ticket-actions"><button onClick={()=>window.print()}><Printer/> Print</button><button><Download/> Download PDF</button><button><Mail/> Send to Email</button><button><CalendarDays/> Add to Calendar</button></div><article className="ticket-document"><header><span>Booking Reference / PNR<b>AW7K9P</b></span><span>E-ticket Number<b>126-9876543210</b></span></header><section><h2>Passenger</h2><div className="ticket-grid"><span>Name<b>{traveler.name}</b></span><span>Passenger type<b>Adult</b></span><span>Passport<b>••••{traveler.passport.slice(-4)}</b></span></div></section><section><h2>Flight Itinerary</h2><div className="ticket-flight"><div><Plane/><span><b>Garuda Indonesia</b><small>GA 980 · Economy · Fare class Y</small></span></div><strong>11:35<small>CGK · Terminal 3</small></strong><i/><strong>18:20<small>JED · Terminal 1</small></strong></div><div className="ticket-grid"><span>Travel date<b>Thursday, 14 May 2026</b></span><span>Seat<b>{seat}</b></span><span>Baggage<b>{fare.bag} checked + 7 kg cabin</b></span><span>Meal<b>Halal Meal</b></span></div></section><section><h2>Payment Summary</h2><div className="ticket-grid"><span>Payment status<b>Paid</b></span><span>Payment method<b>BCA Virtual Account</b></span><span>Total paid<b>{money(total)}</b></span></div></section><section className="checkin-info"><h2>Check-in Information</h2><p>Online check-in opens 48 hours before departure. Arrive at the airport at least 3 hours before your international flight.</p><p><b>Aerowisata Support:</b> +62 21 555 0198 · support@aerowisata.id</p></section><aside className="ticket-code"><div className="qr-pattern"/><span>AW7K9P</span></aside></article><footer><a href="/demo?member=personal&role=Individual%20Member">Manage Booking</a><a href="/demo?member=personal&role=Individual%20Member">View My Trips</a></footer></section>}
