"use client";
import { useState } from "react";
const services=[{icon:"✈",label:"Flights"},{icon:"▥",label:"Hotels"},{icon:"♙",label:"Hajj & Umrah"},{icon:"▱",label:"Transport"},{icon:"◇",label:"Cargo"},{icon:"♨",label:"Tour & Activities"}];
export default function Home(){
 const [activeTab,setActiveTab]=useState("Flights"); const [from,setFrom]=useState("Jakarta (CGK)"); const [to,setTo]=useState("Jeddah (JED)"); const [menuOpen,setMenuOpen]=useState(false);
 const swapRoute=()=>{setFrom(to);setTo(from)};
 return <main>
  <header className="site-header"><a className="brand" href="#" aria-label="Aerowisata home"><span className="brand-mark"><i/><i/><i/></span><span className="brand-copy"><b>Aerowisata</b><small>GARUDA INDONESIA GROUP</small></span></a><button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">☰</button><nav className={menuOpen?"nav open":"nav"} aria-label="Main navigation"><a href="#booking">Flights</a><a href="#services">Hotels</a><a href="#services">Hajj & Umrah</a><a href="#services">Transport</a><a href="#services">Cargo</a><a href="#services">More⌄</a></nav><div className="nav-actions"><a href="#business">Business</a><a href="#business">Government</a><span className="divider"/><button className="locale"><span>🇮🇩</span> ID⌄</button><button className="btn outline">Log In</button><button className="btn primary">Sign Up</button></div></header>
  <section className="hero"><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">AEROWISATA INTEGRATED TRAVEL</p><h1>Every Journey,<br/>Connected.</h1><p className="hero-copy">Flights, stays, transport, and trusted<br className="desktop"/> travel services in one seamless platform.</p><div className="hero-actions"><a className="btn primary large" href="#booking">Explore Services</a><a className="business-link" href="#business">For Business &amp; Government <span>›</span></a></div></div></section>
  <section className="booking" id="booking"><div className="booking-tabs" role="tablist">{services.slice(0,5).map(s=><button key={s.label} className={activeTab===s.label?"active":""} onClick={()=>setActiveTab(s.label)} role="tab"><span>{s.icon}</span>{s.label}</button>)}</div><div className="booking-form"><label><span>From</span><div className="input"><strong>{from.split(" (")[0]}</strong> <small>({from.split("(")[1]}</small><b className="pin">⌖</b></div></label><button className="swap" onClick={swapRoute} aria-label="Swap route">⇄</button><label><span>To</span><div className="input"><strong>{to.split(" (")[0]}</strong> <small>({to.split("(")[1]}</small><b className="pin">⌖</b></div></label><label className="date"><span>Departure</span><div className="input">14 May 2026 <b>▣</b></div></label><label className="passengers"><span>Passengers</span><div className="input">♙ &nbsp; 1 Passenger <b>⌄</b></div></label><button className="btn primary search" onClick={()=>alert(`Searching ${activeTab.toLowerCase()} from ${from} to ${to}`)}>Search {activeTab}</button></div></section>
  <section className="services" id="services"><p className="eyebrow">ONE PLATFORM</p><h2>Everything You Need to Travel</h2><p>From flights to tours, find the right services<br/>to make every journey smooth and meaningful.</p><div className="service-grid">{services.map(s=><a href="#booking" className="service-card" key={s.label}><span>{s.icon}</span><h3>{s.label}</h3></a>)}</div></section>
  <section className="offers"><div className="section-heading"><h2>Offers Curated for Your Journey</h2><a href="#all-offers">View All Offers&nbsp; ›</a></div><div className="offer-row"><article className="umrah-card"><div className="sprite s1"/><div className="umrah-overlay"/><div className="umrah-copy"><p className="eyebrow">HAJJ &amp; UMRAH</p><h3>Umrah Made Easy,<br/>Worship with Peace</h3><p>Trusted packages for a<br/>meaningful spiritual journey.</p><small>From</small><strong>IDR 24.9 Jt</strong><button className="btn aqua">View Package</button></div></article><article className="recommended"><h3>Recommended for You</h3><div className="mini-grid"><div className="mini-card"><div className="sprite s2"/><h4>Flight to Jeddah</h4><small>From</small><strong>IDR 6.1 Jt</strong></div><div className="mini-card"><div className="sprite s3"/><h4>Hotel in Makkah</h4><small>Up to</small><strong>30% OFF</strong></div><div className="mini-card"><div className="sprite s4"/><h4>Airport Transfer</h4><small>From</small><strong>IDR 250 rb</strong></div></div></article><article className="app-card"><div><h3>Aerowisata App</h3><p>All your travel needs<br/>in one app.</p><span className="store">● &nbsp; Download on the<br/><b>App Store</b></span><span className="store">▶ &nbsp; GET IT ON<br/><b>Google Play</b></span></div><div className="sprite s8 phone"/></article></div>
   <div className="enhance"><h3>Enhance Your Journey</h3><p>Add flexible extras to complete your trip.</p><div className="enhance-grid"><article><h4>Hotel in Makkah</h4><div className="sprite s3"/><small>From</small><strong>IDR 1.2 Jt <i>/ night</i></strong></article><article><h4>Airport Transfer</h4><div className="sprite s4"/><small>From</small><strong>IDR 250 rb</strong></article><article><h4>Travel Insurance</h4><div className="sprite s5"/><small>From</small><strong>IDR 75 rb</strong></article><article><h4>Extra Baggage</h4><div className="sprite s6"/><small>From</small><strong>IDR 150 rb</strong></article><article><h4>Food Voucher</h4><div className="sprite s7"/><small>From</small><strong>IDR 50 rb</strong></article></div></div>
  </section>
  <section className="trust-strip"><div><span>♢</span><p><b>Safe &amp; Trusted</b><small>Secure transactions and<br/>reliable protection</small></p></div><div><span>✪</span><p><b>Best Price Guarantee</b><small>Competitive prices for<br/>every journey</small></p></div><div><span>♧</span><p><b>24/7 Customer Support</b><small>Ready to assist you<br/>anytime</small></p></div><div><span>▣</span><p><b>Many Choices</b><small>Integrated services for<br/>every travel need</small></p></div></section>
  <section className="organizations" id="business"><p className="eyebrow">FOR ORGANIZATIONS</p><h2>Travel Solutions Built for Every Organization</h2></section>
 </main>
}
