"use client";
import { useState } from "react";
import { ArrowLeft, BadgeCheck, BriefcaseBusiness, Building2, Check, ChevronDown, CircleUserRound, Eye, EyeOff, Headphones, Landmark, LockKeyhole, Mail, PanelsTopLeft, Plane, ShieldCheck, UserRound } from "lucide-react";

const memberTypes=[
 {id:"personal",code:"B2C",name:"Personal",description:"Individual and family travel",icon:CircleUserRound},
 {id:"business",code:"B2B",name:"Business",description:"Corporate travel management",icon:BriefcaseBusiness},
 {id:"government",code:"B2G",name:"Government",description:"Official government travel",icon:Landmark},
];
const roles:Record<string,{name:string;description:string;icon:any}[]>={
 personal:[{name:"Individual Member",description:"Book and manage personal or family journeys.",icon:UserRound}],
 business:[
  {name:"Corporate Super Admin",description:"Manage company configuration, users, policies, and access.",icon:Building2},{name:"Corporate Admin",description:"Manage employees, travelers, branches, and operational data.",icon:Building2},{name:"Travel Manager",description:"Monitor travel activities, policies, and company spending.",icon:BriefcaseBusiness},{name:"Travel Booker",description:"Book travel for employees, guests, and business groups.",icon:Plane},{name:"Approver",description:"Review, approve, reject, or request travel revisions.",icon:BadgeCheck},{name:"Finance",description:"Manage invoices, payments, credit limits, and reconciliation.",icon:BriefcaseBusiness},{name:"Employee / Traveler",description:"Request and manage individual business travel.",icon:UserRound},{name:"Auditor / Viewer",description:"View transactions, reports, and activity without editing data.",icon:ShieldCheck},
 ],
 government:[
  {name:"Instansi Super Admin",description:"Manage institution configuration, units, and access.",icon:Landmark},{name:"Admin Instansi",description:"Manage users, employees, policies, and master data.",icon:Landmark},{name:"Admin Unit Kerja",description:"Manage travel and employee data for a specific unit.",icon:Building2},{name:"Operator Perjalanan Dinas",description:"Create travel requests and book trips for employees.",icon:Plane},{name:"Pegawai / Pelaksana Perjalanan",description:"Submit travel requests and access tickets and documents.",icon:UserRound},{name:"Atasan / Pejabat Penyetuju",description:"Review and approve official travel requests.",icon:BadgeCheck},{name:"PPK",description:"Validate activities, budgets, and expenditure commitments.",icon:BriefcaseBusiness},{name:"Bendahara",description:"Verify payments and travel accountability documents.",icon:BriefcaseBusiness},{name:"Verifikator Keuangan",description:"Review transaction documents and financial compliance.",icon:ShieldCheck},{name:"Auditor",description:"Review transactions, budgets, documents, and audit trails.",icon:ShieldCheck},
 ],
};

export default function LoginPage(){
 const [showPassword,setShowPassword]=useState(false); const [demoOpen,setDemoOpen]=useState(false); const [member,setMember]=useState(""); const [role,setRole]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const selectedMember=memberTypes.find(m=>m.id===member);
 const submitLogin=(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError("");setTimeout(()=>{setLoading(false);setError("We couldn’t verify those credentials. Please check and try again.")},900)};
 const openDemo=()=>{if(member&&role)window.location.href=`/demo?member=${encodeURIComponent(member)}&role=${encodeURIComponent(role)}`};
 return <main className="auth-page">
  <section className="auth-brand"><div className="auth-overlay"/><a className="auth-logo" href="/"><span className="brand-mark"><i/><i/><i/></span><span className="brand-copy"><b>Aerowisata</b><small>GARUDA INDONESIA GROUP</small></span></a><div className="auth-story"><p>INTEGRATED TRAVEL PLATFORM</p><h1>One Platform,<br/>Every Journey.</h1><span>Seamlessly manage personal trips, corporate travel, and official government journeys.</span></div><div className="auth-trust"><div><ShieldCheck/><span><b>Secure &amp; Trusted</b><small>Protected access</small></span></div><div><Plane/><span><b>Integrated Services</b><small>Travel in one place</small></span></div><div><Headphones/><span><b>24/7 Support</b><small>Always here to help</small></span></div></div></section>
  <section className="auth-main"><div className="auth-mobile-logo"><a className="login-brand" href="/"><span className="brand-mark"><i/><i/><i/></span><span className="brand-copy"><b>Aerowisata</b><small>GARUDA INDONESIA GROUP</small></span></a></div><div className="auth-container"><a className="auth-back" href="/"><ArrowLeft/>Back to home</a><header><h2>Welcome to Aerowisata</h2><p>Sign in to access your travel account.</p></header>
   <form className="auth-form" onSubmit={submitLogin}><label htmlFor="identity">Email or Mobile Number</label><div className="auth-input"><Mail/><input id="identity" placeholder="Enter email or mobile number" required autoComplete="username"/></div><div className="auth-label-row"><label htmlFor="password">Password</label><a href="#forgot">Forgot Password?</a></div><div className="auth-input"><LockKeyhole/><input id="password" type={showPassword?"text":"password"} placeholder="Enter your password" required autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Toggle password visibility">{showPassword?<EyeOff/>:<Eye/>}</button></div><label className="auth-remember"><input type="checkbox"/><span/>Remember Me</label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="auth-submit" disabled={loading}>{loading?<><i/>Signing in…</>:"Log In"}</button></form>
   <div className="auth-divider"><span>or continue with</span></div><div className="social-row"><button><b>G</b>Continue with Google</button><button><PanelsTopLeft/>Continue with Microsoft</button></div>
   <div className="auth-register"><p>Don’t have an account?</p><div><a href="#personal">Create Personal Account</a><a href="#company">Register Your Company</a><a href="#institution">Register Your Institution</a></div></div>
   <section className={demoOpen?"demo-access open":"demo-access"}><button className="demo-toggle" onClick={()=>setDemoOpen(!demoOpen)} aria-expanded={demoOpen}><span><b>Explore Demo Access</b><small>Preview role-based portals without signing in</small></span><ChevronDown/></button>{demoOpen&&<div className="demo-content"><header><h3>Quick Access Demo</h3><p>Preview the platform from different member and user-role perspectives.</p></header><label className="demo-step">1. Select Member Type</label><div className="member-grid">{memberTypes.map(item=>{const Icon=item.icon;const active=member===item.id;return <button className={active?"active":""} key={item.id} onClick={()=>{setMember(item.id);setRole("")}}><Icon/><span><b>{item.name} — {item.code}</b><small>{item.description}</small></span>{active&&<Check className="selected-check"/>}</button>})}</div>{member&&<><label className="demo-step second">2. Select User Role</label><div className="role-grid">{roles[member].map(item=>{const Icon=item.icon;const active=role===item.name;return <button className={active?"active":""} key={item.name} onClick={()=>setRole(item.name)}><Icon/><span><b>{item.name}</b><small>{item.description}</small></span>{active&&<Check className="selected-check"/>}</button>})}</div></>}{member&&role&&<p className="demo-summary">Previewing: <b>{selectedMember?.name} — {role}</b></p>}<button className="demo-submit" disabled={!member||!role} onClick={openDemo}>Open Demo Dashboard</button><p className="demo-disclaimer">Demo access is for platform preview only and does not represent an authenticated production account.</p></div>}</section>
  </div><footer className="auth-footer"><nav><a href="#help">Help Center</a><a href="#privacy">Privacy Policy</a><a href="#terms">Terms &amp; Conditions</a><a href="#contact">Contact Support</a></nav><p>© 2026 Aerowisata. All rights reserved.</p></footer></section>
 </main>
}
