"use client";
import {useState} from "react";
import {ArrowLeft,CalendarDays,CarFront,Check,ChevronDown,Clock3,Fuel,Gauge,MapPin,Search,ShieldCheck,Star,UsersRound} from "lucide-react";

const cars=[
 {name:"Toyota Avanza",type:"MPV",seats:7,transmission:"Automatic",price:475000,badge:"Best Seller",tone:"navy"},
 {name:"Honda BR-V",type:"SUV",seats:7,transmission:"Automatic",price:625000,badge:"Recommended",tone:"blue"},
 {name:"Toyota Innova Zenix",type:"Premium MPV",seats:7,transmission:"Automatic",price:875000,badge:"Premium",tone:"teal"},
 {name:"Honda Brio",type:"City Car",seats:5,transmission:"Automatic",price:365000,badge:"Best Value",tone:"silver"}
];
const money=(n:number)=>`IDR ${n.toLocaleString("id-ID")}`;

export default function RentCar(){
 const [city,setCity]=useState("Jakarta"),[pickup,setPickup]=useState("Soekarno-Hatta International Airport (CGK)"),[date,setDate]=useState("2026-05-14"),[time,setTime]=useState("09:00"),[duration,setDuration]=useState("3"),[driver,setDriver]=useState("With Driver"),[searching,setSearching]=useState(false),[searched,setSearched]=useState(true),[selected,setSelected]=useState<number|null>(null),[filter,setFilter]=useState("All Cars");
 const search=()=>{setSearching(true);setSearched(false);window.setTimeout(()=>{setSearching(false);setSearched(true);document.getElementById("car-results")?.scrollIntoView({behavior:"smooth",block:"start"})},600)};
 const visible=cars.filter(c=>filter==="All Cars"||c.type.includes(filter));
 return <main className="rental-page">
  <header className="rental-header"><a href="/" className="checkout-brand"><span className="brand-mark"><i/><i/><i/></span><span className="brand-copy"><b>Aerowisata</b><small>GARUDA INDONESIA GROUP</small></span></a><nav><a href="/">Flights</a><a href="/#services">Hotels</a><a href="/#services">Transport</a><a className="active">Rent Car</a></nav><div><a href="/login">Log In</a><a className="rent-signup" href="/login">Sign Up</a></div></header>
  <section className="rental-hero"><div><a href="/"><ArrowLeft/> Back to Aerowisata</a><p>CAR RENTAL SERVICE</p><h1>Your Journey,<br/>Your Way.</h1><span>Reliable vehicles, trusted drivers, and flexible rental options for every trip across Indonesia.</span><div className="rental-trust"><b><ShieldCheck/> Verified Partners</b><b><Check/> Transparent Pricing</b><b><Clock3/> 24/7 Support</b></div></div><div className="hero-car"><CarFront/><i/><span>PREMIUM MOBILITY</span></div></section>
  <section className="car-search"><div className="rental-mode"><button className={driver==="With Driver"?"active":""} onClick={()=>setDriver("With Driver")}>With Driver</button><button className={driver==="Self Drive"?"active":""} onClick={()=>setDriver("Self Drive")}>Self Drive</button></div><form onSubmit={e=>{e.preventDefault();search()}}><label><span>City</span><div><MapPin/><select value={city} onChange={e=>setCity(e.target.value)}><option>Jakarta</option><option>Bali</option><option>Surabaya</option><option>Yogyakarta</option><option>Bandung</option></select><ChevronDown/></div></label><label className="pickup"><span>Pickup location</span><div><MapPin/><select value={pickup} onChange={e=>setPickup(e.target.value)}><option>Soekarno-Hatta International Airport (CGK)</option><option>Halim Perdanakusuma Airport (HLP)</option><option>Central Jakarta</option><option>Hotel pickup</option></select><ChevronDown/></div></label><label><span>Pickup date</span><div><CalendarDays/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></label><label><span>Time</span><div><Clock3/><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></div></label><label><span>Duration</span><div><CalendarDays/><select value={duration} onChange={e=>setDuration(e.target.value)}>{[1,2,3,4,5,7,10].map(d=><option value={d} key={d}>{d} day{d>1?"s":""}</option>)}</select><ChevronDown/></div></label><button type="submit" disabled={searching}>{searching?<i/>:<Search/>}{searching?"Searching...":"Search Cars"}</button></form></section>
  <section className="rental-results" id="car-results"><header><div><p>AVAILABLE VEHICLES</p><h2>Find the Right Car for Your Trip</h2><span>{city} · {new Date(`${date}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})} · {duration} days · {driver}</span></div><div className="car-filters">{["All Cars","MPV","SUV","City Car"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></header>{searched?<div className="car-grid">{visible.map((c,i)=><article className={selected===i?"selected":""} key={c.name}><div className={`car-visual ${c.tone}`}><span>{c.badge}</span><CarFront/><i/></div><div className="car-body"><small>{c.type}</small><h3>{c.name}</h3><div className="car-specs"><span><UsersRound/>{c.seats} seats</span><span><Gauge/>{c.transmission}</span><span><Fuel/>Petrol</span></div><ul><li><Check/>Professional driver</li><li><Check/>Fuel & toll estimation</li><li><Check/>Free cancellation up to 24h</li></ul><div className="partner"><span>Operated by AeroTrans</span><b><Star/>4.9</b></div><footer><span>From<small>per day</small><strong>{money(c.price)}</strong></span><button onClick={()=>setSelected(i)}>{selected===i?<><Check/> Selected</>:"Select Car"}</button></footer></div></article>)}</div>:<div className="car-loading">{[1,2,3,4].map(x=><i key={x}/>)}</div>}
  </section>
  <section className="rental-benefits"><div><ShieldCheck/><span><b>Safe & Trusted</b><small>Verified fleets and drivers</small></span></div><div><Check/><span><b>No Hidden Fees</b><small>Clear pricing before checkout</small></span></div><div><Clock3/><span><b>Flexible Rental</b><small>Daily and extended options</small></span></div><div><Star/><span><b>Quality Guaranteed</b><small>Well-maintained vehicles</small></span></div></section>
  {selected!==null&&<div className="mobile-rent-bar"><span><small>{cars[selected].name} · {duration} days</small><b>{money(cars[selected].price*Number(duration))}</b></span><button onClick={()=>location.href="/login"}>Continue</button></div>}
 </main>
}
